# Generated by Django 5.2.7 on 2025-10-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('length', models.PositiveIntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.PositiveIntegerField()),
                ('word_count', models.PositiveIntegerField()),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
